add documentation on COUCH2PG_USERS_META_DOC_LIMIT and add safeNum safety
medic/cht-couch2pg pull request #100
Opened 2021-07-06 14:24 UTC by njogz

Add documentation about the `COUCH2PG_USERS_META_DOC_LIMIT` environment variable and add safeNum safety check

2021-07-06 15:19 UTC, mrsarm requested changes
Hey, thanks for taken this! I also linked the PR to another issue that requested the same changes.

2021-07-06 15:19 UTC, mrsarm commented on README.md
> +| COUCH2PG_USERS_META_DOC_LIMIT | Number of documents from users-meta database that cht-couch2pg fetches from CouchDB everytime |
The description seems incomplete, making the variable to look like it sets a limit on how much documents are fetched in total or in total in a batch, while in reality the value is set to limit the number of documents *per* fetch. A good description I found is [here](https://github.com/medic/cht-couch2pg/blob/3e38727075c0132fad3f3e41c4a4461b202519de/inquirer.js#L65), and would be nice to also add in the description what is the default value taken when the variable is not set.

Also would be nice if you can add in the documentation what is the default value taken in the rest of the variables or at least where to check the default values _(inquirer.js)_.

2021-07-07 12:19 UTC, mrsarm approved these changes
LGTM :+1:

2021-07-08 08:55 UTC, yrimal approved these changes

2021-09-16 13:48 UTC, merged